#!/bin/bash
pushd /etc/apache2/sites-enabled/
ln -s ../sites-available/hostdb hostdb
popd

[ -d /var/lib/hostdb ] || mkdir /var/lib/hostdb
[ -d /var/log/hostdb ] || mkdir /var/log/hostdb

chown -R www-data:www-data /etc/hostdb /var/lib/hostdb /var/log/hostdb /var/www
chown root:root /etc/cron.d/hostdb*
chown root:root /etc/logrotate.d/hostdb

KEY_FILE=`grep cipher_key_file /etc/hostdb/server_conf.yaml |awk '{print $2}'`
[ -e "$KEY_FILE" ] || date | md5sum | cut -c1-8 > $KEY_FILE
chmod 400 $KEY_FILE
chown www-data:www-data $KEY_FILE

a2enmod fcgid
a2enmod rewrite
a2enmod ssl
/etc/init.d/apache2 reload

exit 0
